### ISSUE TITLE
no learn.md

### ISSUE THREAD

**Issue by DesignDread** [Curious-Ecosystem/Curious-Connect#201]
### Issue Description

i am a begginer and unable to run the program in my pc i want a learn.md for this

### Checklist

- [X] I have checked the existing [issues](https://github.com/Curious-Ecosystem/Curious-Connect/issues).
- [X] I have read the [Contributing Guidelines](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CONTRIBUTING.md)
- [X] I have read the [Code Of Conduct](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CODE_OF_CONDUCT.md)
- [X] I joined onboarding group for knowledge flow and direct conversation and support from admins  [Curious Developers Community - Curious Connect](https://chat.whatsapp.com/FR0sVnpsSvL4J4l56vLdBN)
- [X] The changes don't break the code
- [X] Please attach the screenshots and video of the development work once it is done 
- [X] If you need any help please join the default  ([Google Meet Link](https://meet.google.com/bwp-aasw-xbk))

**Comment by CDCNaman** [comment]
@DesignDread Sorry for late reply but instead of learn.md, you can also follow our ReadMe File it contains link to all other related Documents. For Running our program you can read [Project Setup](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/docs/Project_Setup.md) 
If you still have any questions Please onboard yourself to our WhatsApp Group [Curious Developers Community - GSSoC ](https://chat.whatsapp.com/FR0sVnpsSvL4J4l56vLdBN) and connect with our admins
